### ISSUE TITLE
ScanMixin does not understand drift scans

### ISSUE THREAD

**Issue by etsmit** [GreenBankObservatory/dysh#256]
Summary: When trying to load in some test driftscan data, the timeaverage() function breaks as it doesn't understand the coordinate system when using the inherited astropy methods.

Recently, we tried to load in some test data that was taken during maintenance - while the telescope was locked in position. The point of this test data was to inject a test tone at a known frequency, take a short scan, and ensure it passes through the IF/LO system without drifting/shifting more than a few tens of Hz. This is done with the astrid command "Track(GetCurrentLocation("Encoder"), None, 30)" (see footnote). It essentially results in an SDFITS file with all blanks under the RADESYS column.

The file loads in OK as a GBTFITSLoad object, and I can retrieve e.g. "tpscan = sdf.gettp(scan=X,plnum=Y)" with no complaint. However, when running "tpscan.timeaverage()" I get the following traceback:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[128], line 1
----> 1 tpscan.timeaverage()

File ~/Git/dysh/src/dysh/spectra/scan.py:197, in ScanBlock.timeaverage(self, weights, mode)
    195 self._timeaveraged = []
    196 for scan in self.data:
--> 197     self._timeaveraged.append(scan.timeaverage(weights))
    198 if weights == "tsys":
    199     # There may be multiple integrations, so need to
    200     # average the Tsys weights
    201     w = np.array([np.nanmean(k._tsys_weight) for k in self.data])

File ~/Git/dysh/src/dysh/spectra/scan.py:512, in TPScan.timeaverage(self, weights)
    510 if self._npol > 1:
    511     raise Exception("Can't yet time average multiple polarizations")
--> 512 self._timeaveraged = deepcopy(self.total_power(0))
    513 if weights == "tsys":
    514     w = self._tsys_weight

File ~/Git/dysh/src/dysh/spectra/scan.py:492, in TPScan.total_power(self, i)
    490 restfreq = rfq.to("Hz").value
    491 meta["RESTFRQ"] = restfreq  # WCS wants no E
--> 492 return Spectrum.make_spectrum(self._data[i] * u.ct, meta, observer_location=self._observer_location)

File ~/Git/dysh/src/dysh/spectra/spectrum.py:534, in Spectrum.make_spectrum(cls, data, meta, use_wcs, observer_location)
    532     wcs = None
    533 # is_topo = is_topocentric(meta["CTYPE1"])  # GBT-specific to use CTYPE1 instead of VELDEF
--> 534 target = make_target(meta)
    535 vc = veldef_to_convention(meta["VELDEF"])
    536 vf = astropy_frame_dict[decode_veldef(meta["VELDEF"])[1]]

File ~/Git/dysh/src/dysh/coordinates/core.py:475, in make_target(header)
    472 if not _required <= header.keys():
    473     raise ValueError(f"Header is missing one or more required keywords: {_required}")
--> 475 t1 = coord.SkyCoord(
    476     header["CRVAL2"],
    477     header["CRVAL3"],
    478     unit=(header["CUNIT2"], header["CUNIT3"]),
    479     frame=header["RADESYS"].lower(),
    480     radial_velocity=header["VELOCITY"] * _MPS,
    481     distance=_DEFAULT_DISTANCE,  # need this or PMs get units m rad /s !
    482 )
    483 # print(f"{t1},{t1.pm_ra_cosdec},{t1.pm_dec},{t1.distance},{t1.radial_velocity}")
    484 target = sanitize_skycoord(t1)

File ~/.conda/envs/dyshpy/lib/python3.9/site-packages/astropy/coordinates/sky_coordinate.py:333, in SkyCoord.__init__(self, copy, *args, **kwargs)
    327         self._sky_coord_frame = coords
    329 else:
    330     # Get the frame instance without coordinate data but with all frame
    331     # attributes set - these could either have been passed in with the
    332     # frame as an instance, or passed in as kwargs here
--> 333     frame_cls, frame_kwargs = _get_frame_without_data(args, kwargs)
    335     # Parse the args and kwargs to assemble a sanitized and validated
    336     # kwargs dict for initializing attributes for this object and for
    337     # creating the internal self._sky_coord_frame object
    338     args = list(args)  # Make it mutable

File ~/.conda/envs/dyshpy/lib/python3.9/site-packages/astropy/coordinates/sky_coordinate_parsers.py:143, in _get_frame_without_data(args, kwargs)
    140         kwargs.setdefault("differential_type", frame.differential_type)
    142     if frame_cls is None:  # frame probably a string
--> 143         frame_cls = _get_frame_class(frame)
    145 # Check that the new frame doesn't conflict with existing coordinate frame
    146 # if a coordinate is supplied in the args list.  If the frame still had not
    147 # been set by this point and a coordinate was supplied, then use that frame.
    148 for arg in args:
    149     # this catches the "single list passed in" case.  For that case we want
    150     # to allow the first argument to set the class.  That's OK because
    151     # _parse_coordinate_arg goes and checks that the frames match between
    152     # the first and all the others

File ~/.conda/envs/dyshpy/lib/python3.9/site-packages/astropy/coordinates/sky_coordinate_parsers.py:47, in _get_frame_class(frame)
     45     frame_names = frame_transform_graph.get_names()
     46     if frame not in frame_names:
---> 47         raise ValueError(
     48             f'Coordinate frame name "{frame}" is not a known '
     49             f"coordinate frame ({sorted(frame_names)})"
     50         )
     51     frame_cls = frame_transform_graph.lookup_name(frame)
     53 elif isinstance(frame, type) and issubclass(frame, BaseCoordinateFrame):

ValueError: Coordinate frame name "" is not a known coordinate frame (['altaz', 'barycentricmeanecliptic', 'barycentrictrueecliptic', 'cirs', 'custombarycentricecliptic', 'fk4', 'fk4noeterms', 'fk5', 'galactic', 'galacticlsr', 'galactocentric', 'gcrs', 'geocentricmeanecliptic', 'geocentrictrueecliptic', 'hadec', 'hcrs', 'heliocentriceclipticiau76', 'heliocentricmeanecliptic', 'heliocentrictrueecliptic', 'icrs', 'itrs', 'lsr', 'lsrd', 'lsrk', 'precessedgeocentric', 'supergalactic', 'teme', 'tete'])

```

So the inherited astropy methods don't understand when the coordinate system is blank. I'm not exactly sure what possible solutions could get around this - we could fudge that column under the hood, but that may be assuming too much about the observer's intentions.

The specific data file is `/home/sdfits/TSCI_RYAN_16/TSCI_RYAN_16.raw.vegas/TSCI_RYAN_16.raw.vegas.A.fits`. 

Furthermore, there is another issue with the data which I will write in a new entry and suspect is related to [Issue 133](https://github.com/GreenBankObservatory/dysh/issues/133) - that is, this data is taken with no calibration diode switching. In GBTIDL, running a gettp on this scan returns a spectrum without complaint, but with Tsys=1.0. In dysh, we error out with the message "unbalanced calrows 0 != 16". More info in the other entry.

**Environment**
- Dysh version 0.3.0
- Python version 3.9.16
- astropy 6.0.1
- OS Redhat 7

Footnote: (Correct me if I'm wrong @astrofle ) For drift scans, or any scan taken while the telescope is locked out of movement (during maintenance etc.) we take data using this command as it sets the start location (on the sky) as where the telescope is currently pointed, so it doesn't think it has to start with any movement. During the scan, the telescope will try to track that same sky position, but the operator will have taken the Antenna Manager out of the Scan Coordinator - which means those commands to move the telescope fall on deaf ears and the telescope doesn't move. I'm not exactly sure how this results in a blank RADESYS column in the SDFITS files. (Don't worry there are still several more redundant levels of braking and locking systems in place even if the antenna was still commanded to move)

**Comment by etsmit** [comment]
This is not a solution, but the generic cause of this is indeed because the Antenna Manager was not in the Scan coordinator, which meant the sdfits did not fill (among other things) the RADESYS column, azimuth and elevation, and LST, of which the latter 3 are all zeroes.

**Comment by astrofle** [comment]
`GBTIDL` uses the azimuth and elevation values. A possible solution would be to define the `RADESYS` column based on `CTYPE2` and `CTYPE3` when `RADESYS` is empty (I think this is what GBTIDL does in one way or another).

**Comment by astrofle** [comment]
https://github.com/GreenBankObservatory/dysh/pull/264 should fix this, although I have not thoroughly tested it yet.

**Comment by etsmit** [comment]
For posterity, the SDFITS columns that seem to be affected by the missing Antenna Fits files are:

zeros:
- LST
- azimuth
- elevatio
- tambient
- pressure
- humidity
- equinox
- trgtlong
- trgtlat

blank:
- radesys

other things which are zero'd out in the test file but because they're not used in L-band:
- subreflector offsets
- dynamic corrections
- quadrant detector stuff

**Comment by jfrothingham** [comment]
Hello! Reporting that this bug is still active. 

I ran` /home/dysh/release/stable/bin/dysh-lab` to start and am working in a jupyter notebook on a Green Bank data reduction machine (maxwell). Dysh version is 0.3.0. 

I'm working with total power "Track" data, files at `'/home/sdfits/AGBT24A_329_02/AGBT24A_329_02.raw.vegas'`. Attempts to use timeaverage() and plot() are met with the error messages pasted below. I checked the FITS files and messaged with @etsmit . The RADESYS column is blank. The AZIMUTH and ELEVATION columns have values. The scan does have noise diode switching.


---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[53], line 3
      1 for i in range(0, 2*len(tpscanarray)):
      2     currentscan = tpscanarray[i]
----> 3     currentscan.timeaverage().plot()

File /home/dysh/release/0.3/dysh/src/dysh/spectra/scan.py:203, in ScanBlock.timeaverage(self, weights, mode)
    201 self._timeaveraged = []
    202 for scan in self.data:
--> 203     self._timeaveraged.append(scan.timeaverage(weights))
    204 if weights == "tsys":
    205     # There may be multiple integrations, so need to
    206     # average the Tsys weights
    207     w = np.array([np.nanmean(k._tsys_weight) for k in self.data])

File /home/dysh/release/0.3/dysh/src/dysh/spectra/scan.py:518, in TPScan.timeaverage(self, weights)
    516 if self._npol > 1:
    517     raise Exception("Can't yet time average multiple polarizations")
--> 518 self._timeaveraged = deepcopy(self.total_power(0))
    519 if weights == "tsys":
    520     w = self._tsys_weight

File /home/dysh/release/0.3/dysh/src/dysh/spectra/scan.py:498, in TPScan.total_power(self, i)
    496 restfreq = rfq.to("Hz").value
    497 meta["RESTFRQ"] = restfreq  # WCS wants no E
--> 498 return Spectrum.make_spectrum(self._data[i] * u.ct, meta, observer_location=self._observer_location)

File /home/dysh/release/0.3/dysh/src/dysh/spectra/spectrum.py:600, in Spectrum.make_spectrum(cls, data, meta, use_wcs, observer_location)
    598     wcs = None
    599 # is_topo = is_topocentric(meta["CTYPE1"])  # GBT-specific to use CTYPE1 instead of VELDEF
--> 600 target = make_target(meta)
    601 vc = veldef_to_convention(meta["VELDEF"])
    602 vf = astropy_frame_dict[decode_veldef(meta["VELDEF"])[1]]

File /home/dysh/release/0.3/dysh/src/dysh/coordinates/core.py:504, in make_target(header)
    501 if not _required <= header.keys():
    502     raise ValueError(f"Header is missing one or more required keywords: {_required}")
--> 504 t1 = coord.SkyCoord(
    505     header["CRVAL2"],
    506     header["CRVAL3"],
    507     unit=(header["CUNIT2"], header["CUNIT3"]),
    508     frame=header["RADESYS"].lower(),
    509     radial_velocity=header["VELOCITY"] * _MPS,
    510     distance=_DEFAULT_DISTANCE,  # need this or PMs get units m rad /s !
    511     obstime=Time(header["DATE-OBS"]),
    512     location=gbt_location(),
    513 )
    514 # print(f"{t1},{t1.pm_ra_cosdec},{t1.pm_dec},{t1.distance},{t1.radial_velocity}")
    515 target = sanitize_skycoord(t1)

File /home/dysh/release/0.3/dysh-rhel7-env/lib/python3.11/site-packages/astropy/coordinates/sky_coordinate.py:333, in SkyCoord.__init__(self, copy, *args, **kwargs)
    327         self._sky_coord_frame = coords
    329 else:
    330     # Get the frame instance without coordinate data but with all frame
    331     # attributes set - these could either have been passed in with the
    332     # frame as an instance, or passed in as kwargs here
--> 333     frame_cls, frame_kwargs = _get_frame_without_data(args, kwargs)
    335     # Parse the args and kwargs to assemble a sanitized and validated
    336     # kwargs dict for initializing attributes for this object and for
    337     # creating the internal self._sky_coord_frame object
    338     args = list(args)  # Make it mutable

File /home/dysh/release/0.3/dysh-rhel7-env/lib/python3.11/site-packages/astropy/coordinates/sky_coordinate_parsers.py:144, in _get_frame_without_data(args, kwargs)
    141         kwargs.setdefault("differential_type", frame.differential_type)
    143     if frame_cls is None:  # frame probably a string
--> 144         frame_cls = _get_frame_class(frame)
    146 # Check that the new frame doesn't conflict with existing coordinate frame
    147 # if a coordinate is supplied in the args list.  If the frame still had not
    148 # been set by this point and a coordinate was supplied, then use that frame.
    149 for arg in args:
    150     # this catches the "single list passed in" case.  For that case we want
    151     # to allow the first argument to set the class.  That's OK because
    152     # _parse_coordinate_arg goes and checks that the frames match between
    153     # the first and all the others

File /home/dysh/release/0.3/dysh-rhel7-env/lib/python3.11/site-packages/astropy/coordinates/sky_coordinate_parsers.py:48, in _get_frame_class(frame)
     46     frame_names = frame_transform_graph.get_names()
     47     if frame not in frame_names:
---> 48         raise ValueError(
     49             f'Coordinate frame name "{frame}" is not a known '
     50             f"coordinate frame ({sorted(frame_names)})"
     51         )
     52     frame_cls = frame_transform_graph.lookup_name(frame)
     54 elif inspect.isclass(frame) and issubclass(frame, BaseCoordinateFrame):

ValueError: Coordinate frame name "" is not a known coordinate frame (['altaz', 'barycentricmeanecliptic', 'barycentrictrueecliptic', 'cirs', 'custombarycentricecliptic', 'fk4', 'fk4noeterms', 'fk5', 'galactic', 'galacticlsr', 'galactocentric', 'gcrs', 'geocentricmeanecliptic', 'geocentrictrueecliptic', 'hadec', 'hcrs', 'heliocentriceclipticiau76', 'heliocentricmeanecliptic', 'heliocentrictrueecliptic', 'icrs', 'itrs', 'lsr', 'lsrd', 'lsrk', 'precessedgeocentric', 'supergalactic', 'teme', 'tete'])

**Comment by astrofle** [comment]
Thanks a lot Jay. I can confirm that this is not fixed following your example. We'll see how this can be fixed and let you know once it is resolved.

**Comment by astrofle** [comment]
@Marc the problem seems to come from updating `GBTFITSLoad.index` but not `GBTFITSLoad._sdf[0].index`, which gets passed to the `TPScan`.  Should both be updated or should we be passing the `GBTFITSLoad.index` to the `Scan` instead?
